# Generated by Django 4.2.7 on 2025-11-22 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('CLUB_EXECUTIVE', 'Membre exécutif de club'), ('AESI_EXECUTIVE', 'Membre exécutif AESI')], default='STUDENT', max_length=20, verbose_name='rôle')),
                ('filiere', models.CharField(blank=True, choices=[('IDA', "Licence Professionnelle en Analyse Statistique"), ('ITS', 'Ingénieur Economiste Statisticien(ne)'), ('TSE', "Licence en Santé et Population'Économie"), ('TS', 'Technicien Supérieur de la Statistique'), ('AT', 'Master de Recherche en Démographie')], max_length=10, verbose_name='filière')),
                ('niveau', models.CharField(blank=True, choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année'), ('4', '4ème année')], max_length=2, verbose_name='niveau')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='authentification à deux facteurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
