# Generated by Django 4.2.7 on 2025-11-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Étudiant'), ('CLUB_EXECUTIVE', 'Membre exécutif de club'), ('AESI_TREASURER', 'Trésorier AESI'), ('AESI_EXECUTIVE', 'Membre exécutif AESI')], default='STUDENT', max_length=20, verbose_name='rôle'),
        ),
    ]
