# Generated by Django 4.2.7 on 2025-11-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Étudiant'), ('CLUB_EXECUTIVE', 'Membre exécutif du club'), ('AESI_TREASURER', "Trésorier de l'AESI")], default='STUDENT', max_length=20, verbose_name='rôle'),
        ),
    ]
