# Generated by Django 4.2.7 on 2025-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, choices=[('IDA', 'Licence Professionnelle en Analyse Statistique'), ('ITS', 'Ingénieur Economiste Statisticien(ne)'), ('TSE', "Licence en Santé et Population'Économie"), ('TS', 'Master Professionnelle en Démographie'), ('AT', 'Master de Recherche en Démographie')], max_length=10, verbose_name='filière'),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau',
            field=models.CharField(blank=True, choices=[('1', '1ère année'), ('2', '2ème année'), ('3', '3ème année')], max_length=2, verbose_name='niveau'),
        ),
    ]
