# Generated by Django 4.2.7 on 2025-11-22 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
            ],
            options={
                'verbose_name': "programme d'action",
                'verbose_name_plural': "programmes d'action",
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('theme', models.CharField(max_length=200, verbose_name='thème')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='heure')),
                ('location', models.CharField(max_length=200, verbose_name='lieu')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('ONGOING', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='statut')),
                ('otp_enabled', models.BooleanField(default=True, verbose_name='OTP activé')),
                ('difficulties', models.TextField(blank=True, verbose_name='difficultés rencontrées')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='activities/covers/', verbose_name='image de couverture')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to='activities/photos/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
            ],
            options={
                'verbose_name': "photo d'activité",
                'verbose_name_plural': "photos d'activités",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('INFORMATIQUE', "Club d'Informatique"), ('ANGLAIS', "Club d'Anglais"), ('ART_ORATOIRE', "Club d'Art Oratoire"), ('SPORT', 'Club de Sport')], max_length=20, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='clubs/covers/', verbose_name='image de couverture')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'club',
                'verbose_name_plural': 'clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('position', models.CharField(choices=[('PRESIDENT', 'Coordinateur(trice)'), ('SECRETARY', 'Secrétaire'), ('TREASURER', 'Trésorier(ère)'), ('COMMUNICATION', 'Organisateur(trice)'), ('MEMBER', 'Membre')], max_length=20, verbose_name='poste')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'membre exécutif',
                'verbose_name_plural': 'membres exécutifs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'compétition',
                'verbose_name_plural': 'compétitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_present', models.BooleanField(default=False, verbose_name='présent')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'assiduité membre',
                'verbose_name_plural': 'assiduités membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('due_date', models.DateField(verbose_name='date limite')),
                ('is_completed', models.BooleanField(default=False, verbose_name='complété')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='rang')),
                ('prize', models.CharField(blank=True, max_length=200, verbose_name='prix')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='clubs.competition', verbose_name='compétition')),
            ],
            options={
                'verbose_name': 'gagnant',
                'verbose_name_plural': 'gagnants',
                'ordering': ['rank'],
            },
        ),
    ]
