# Generated by Django 5.2 on 2025-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='missions',
            field=models.TextField(blank=True, help_text='Décrivez les missions et responsabilitéssspécifiques de ce membre', verbose_name='missions spécifiques'),
        ),
    ]
