# Generated by Django 4.2.7 on 2025-11-28 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0003_clubmember_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cancellation_comment',
            field=models.TextField(blank=True, verbose_name="commentaire d'annulation"),
        ),
        migrations.AddField(
            model_name='activity',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'annulation"),
        ),
        migrations.AddField(
            model_name='activity',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de complétion'),
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(help_text='PDF, Word, Excel, PowerPoint, ZIP, etc.', upload_to='activities/resources/', verbose_name='fichier')),
                ('resource_type', models.CharField(choices=[('PDF', 'Document PDF'), ('DOC', 'Document Word'), ('XLS', 'Document Excel'), ('PPT', 'Présentation PowerPoint'), ('ZIP', 'Archive ZIP'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='type de ressource')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='clubs.activity', verbose_name='activité')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='téléchargé par')),
            ],
            options={
                'verbose_name': "ressource d'activité",
                'verbose_name_plural': "ressources d'activités",
                'ordering': ['-created_at'],
            },
        ),
    ]
