# Generated by Django 4.2.7 on 2025-11-22 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP vérifié')),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP vérifié le')),
                ('appreciation', models.TextField(blank=True, verbose_name='appréciation')),
                ('suggestion', models.TextField(blank=True, verbose_name='suggestion')),
                ('rating', models.IntegerField(blank=True, help_text='Note de 1 à 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='participation/photos/', verbose_name='photo 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='participation/photos/', verbose_name='photo 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='participation/photos/', verbose_name='photo 3')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
            ],
            options={
                'verbose_name': 'participation',
                'verbose_name_plural': 'participations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participations', models.IntegerField(default=0, verbose_name='total participations')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='note moyenne')),
                ('informatique_count', models.IntegerField(default=0, verbose_name='participations informatique')),
                ('anglais_count', models.IntegerField(default=0, verbose_name='participations anglais')),
                ('art_oratoire_count', models.IntegerField(default=0, verbose_name='participations art oratoire')),
                ('sport_count', models.IntegerField(default=0, verbose_name='participations sport')),
                ('total_wins', models.IntegerField(default=0, verbose_name='total victoires')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'statistique de participation',
                'verbose_name_plural': 'statistiques de participation',
            },
        ),
    ]
