# Generated by Django 5.2 on 2025-11-23 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmember_missions'),
        ('participation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicParticipationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('otp_code', models.CharField(max_length=6, verbose_name='code OTP')),
                ('otp_generated_at', models.DateTimeField(auto_now_add=True, verbose_name='OTP généré le')),
                ('otp_expires_at', models.DateTimeField(verbose_name='OTP expire le')),
                ('form_link', models.CharField(max_length=255, unique=True, verbose_name='lien du formulaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('access_count', models.IntegerField(default=0, verbose_name="nombre d'accès")),
                ('submission_count', models.IntegerField(default=0, verbose_name='nombre de soumissions')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form', to='clubs.activity', verbose_name='activité')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'formulaire de participation dynamique',
                'verbose_name_plural': 'formulaires de participation dynamiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
